### ISSUE TITLE
新的改动需要发布一个版本

### ISSUE THREAD

**Issue by SettingDust** [Rabbitzzc/js-string-comparison#12]

**Comment by Rabbitzzc** [comment]
最近好像没有做调整，还没规划呢。最近太忙了

**Comment by SettingDust** [comment]
> 最近好像没有做调整，还没规划呢。最近太忙了

有的，而且还没发布，是动态导入的改动，被折磨了好几天
https://github.com/ndaidong/article-parser/issues/206#issuecomment-1030645918 到 https://github.com/ndaidong/article-parser/issues/206#issuecomment-1039095412

**Comment by Rabbitzzc** [comment]
我这边已经处理好了，使用 `1.1.0` 版本试试
