### ISSUE TITLE
Jaro-Winkler

### ISSUE THREAD

**Issue by Vectoras** [Rabbitzzc/js-string-comparison#17]
Is the **Jaro-Winkler** algorithm being implemented or not?

In the documentation I can see it in the table but not in the API

**Comment by Rabbitzzc** [comment]
no, please share me a url about the  Jaro-Winkler algorithm

**Comment by Vectoras** [comment]
i don't know much about it myself. I have a use case where I need to compare names and I chose this library due to the fact that it implements multiple algorithms.

That being said, here are a few links to pages about Jaro-Winkler algorithm:
- [https://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance#See_also](https://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance#See_also)
- [https://www.geeksforgeeks.org/jaro-and-jaro-winkler-similarity/#](https://www.geeksforgeeks.org/jaro-and-jaro-winkler-similarity/#)
- [https://www.statology.org/jaro-winkler-similarity/](https://www.statology.org/jaro-winkler-similarity/)

And here a paper about various string metrics for matching names and records which I believe touches various algorithms: [https://www.cs.cmu.edu/afs/cs/Web/People/wcohen/postscript/kdd-2003-match-ws.pdf](https://www.cs.cmu.edu/afs/cs/Web/People/wcohen/postscript/kdd-2003-match-ws.pdf)
Here another paper about comparing names: http://users.cecs.anu.edu.au/~Peter.Christen/publications/tr-cs-06-02.pdf

I hope they help.

**Comment by Rabbitzzc** [comment]
done - https://github.com/Rabbitzzc/js-string-comparison/commit/6a7d2825089ae94faa8cbddd52ffd720d9a5ea6c
