### ISSUE TITLE
Typos in readme for install and sample code

### ISSUE THREAD

**Issue by colin-brown** [Rabbitzzc/js-string-comparison#8]
The installation instructions use the package name `string-comparision` but the actual package name is `string-comparison`

To install the instructions should read:

`npm install string-comparison --save`

The sample code has a line which should be commented out:

`// use Consine`

..and the method name has a typo, it should be `cosine` not `consine`. Correct line should be:

`let cos = stringComparision.cosine`

**Comment by Rabbitzzc** [comment]
thks...
